### ISSUE TITLE
Incorrect .mobi file?

### ISSUE THREAD

**Issue by brentonsmith** [coljac/kindle_eo_eng#1]
Thanks for compiling this, i'm just starting to try reading Esperanto books on my kindle and a good dictionary would be great -- but i've found the others are missing a lot of basic words.

Unfortunately, I don't think the provided .mobi file in the readme here is the correct .mobi for the tsv file however? As an example, the definition for fakte is different and flegistinoj (and many other words) are absent.

**Comment by crvdgc** [comment]
Saluton. I compiled the tsv file to [a new mobi file](https://github.com/crvdgc/kindle_eo_eng/releases/download/0.0.1/Combined_Esperanto_English.mobi) in [my fork](https://github.com/crvdgc/kindle_eo_eng), because the link in the README is dead. Also I'm using the latest version of tab2opf. Maybe this will solve the problem?

**Comment by coljac** [comment]
Fixed - apologies for the delay. The readme is now correct. 

[Esperanto-English.zip](https://github.com/coljac/kindle_eo_eng/files/5044520/Esperanto-English.zip)
